version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile # If you have a Dockerfile for the client app
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server/cmd
      dockerfile: Dockerfile # If you have a Dockerfile for the server app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI port