networks:
  internal:
    driver: bridge

services:
  client:
    build:
      context: ./client
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - internal

  server:
    build:
      context: ./server/cmd
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal